<?php 
/**
 *  Install Add-ons
 *  
 *  The following code will include all 4 premium Add-Ons in your theme.
 *  Please do not attempt to include a file which does not exist. This will produce an error.
 *  
 *  All fields must be included during the 'acf/register_fields' action.
 *  Other types of Add-ons (like the options page) can be included outside of this action.
 *  
 *  The following code assumes you have a folder 'add-ons' inside your theme.
 *
 *  IMPORTANT
 *  Add-ons may be included in a premium theme as outlined in the terms and conditions.
 *  However, they are NOT to be included in a premium / free plugin.
 *  For more information, please read http://www.advancedcustomfields.com/terms-conditions/
 */ 

// Fields 
// add_action('acf/register_fields', 'my_register_fields');

function my_register_fields()
{
    //include_once('add-ons/acf-repeater/repeater.php');
    //include_once('add-ons/acf-gallery/gallery.php');
    //include_once('add-ons/acf-flexible-content/flexible-content.php');
}

// Options Page 
//include_once( 'add-ons/acf-options-page/acf-options-page.php' );


/**
 *  Register Field Groups
 *
 *  The register_field_group function accepts 1 array which holds the relevant data to register a field group
 *  You may edit the array as you see fit. However, this may result in errors if the array is not compatible with ACF
 */

if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_general',
        'title' => 'General',
        'fields' => array (
            array (
                'key' => 'field_5162f717d58b1',
                'label' => 'Images',
                'name' => 'images',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5162edfb61d54',
                'label' => 'Logo',
                'name' => 'logo',
                'type' => 'image',
                'save_format' => 'url',
                'preview_size' => 'full',
            ),
            array (
                'key' => 'field_5162f0c8392b6',
                'label' => 'Spinner',
                'name' => 'spinner',
                'type' => 'image',
                'instructions' => 'Custom loader image.',
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
            ),
            array (
                'key' => 'field_5162ee6f3fd25',
                'label' => 'Favicon',
                'name' => 'favicon',
                'type' => 'file',
                'save_format' => 'url',
            ),
            array (
                'key' => 'field_5162f72c26541',
                'label' => 'Setup',
                'name' => 'setup',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5162eecb26ee9',
                'label' => 'No Pages Reload',
                'name' => 'no_pages_reload',
                'type' => 'true_false',
                'instructions' => 'Every section of the website is loaded through Ajax and managed with Html5 push state (where supported).',
                'message' => 'activate ajax load & html5 push state',
                'default_value' => 1,
            ),
            array (
                'key' => 'field_5163fee96d73c',
                'label' => 'Audio Player',
                'name' => 'audio_player',
                'type' => 'true_false',
                'instructions' => 'You also need to upload mp3 / ogg tracks in order to display the audio player.',
                'message' => 'Display audio player',
                'default_value' => 1,
            ),
            array (
                'key' => 'field_51640962b6949',
                'label' => 'Audio Player Autoplay',
                'name' => 'audio_player_autoplay',
                'type' => 'true_false',
                'message' => 'Autoplay on startup',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_516330cc514d5',
                'label' => 'Social Networks',
                'name' => 'social_networks',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5187b336ec112',
                'label' => '500px url',
                'name' => 'social_500px',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b3ceec113',
                'label' => 'Behance Url',
                'name' => 'social_behance',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b467ec114',
                'label' => 'Blogger Url',
                'name' => 'social_blogger',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b473ec115',
                'label' => 'Deviant Art Url',
                'name' => 'social_deviantart',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b4aa9cd6b',
                'label' => 'Digg Url',
                'name' => 'social_digg',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b4b29cd6c',
                'label' => 'Dribbble Url',
                'name' => 'social_dribbble',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b4c19cd6d',
                'label' => 'Email Address',
                'name' => 'social_email',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b4d29cd6e',
                'label' => 'Envato Url',
                'name' => 'social_envato',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b4da9cd6f',
                'label' => 'Facebook Url',
                'name' => 'social_facebook',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b4e59cd70',
                'label' => 'Flickr Url',
                'name' => 'social_flickr',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b4f09cd71',
                'label' => 'Forrst Url',
                'name' => 'social_forrst',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b4fb9cd72',
                'label' => 'Github Url',
                'name' => 'social_github',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b5059cd73',
                'label' => 'Google Plus Url',
                'name' => 'social_google-plus',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b5f896d61',
                'label' => 'Grooveshark Url',
                'name' => 'social_grooveshark',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b60496d62',
                'label' => 'Last Fm Url',
                'name' => 'social_last-fm',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b61696d63',
                'label' => 'Linkedin Url',
                'name' => 'social_linkedin',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b62596d64',
                'label' => 'Myspace Url',
                'name' => 'social_myspace',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b63a96d65',
                'label' => 'Paypal Url',
                'name' => 'social_paypal',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b64796d66',
                'label' => 'Photobucket Url',
                'name' => 'social_photobucket',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b65596d67',
                'label' => 'Pinterest Url',
                'name' => 'social_pinterest',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b66196d68',
                'label' => 'Quora Url',
                'name' => 'social_quora',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b66d96d69',
                'label' => 'Soundcloud Url',
                'name' => 'social_soundcloud',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b78396d6a',
                'label' => 'Stumbleupon Url',
                'name' => 'social_stumbleupon',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b78c96d6b',
                'label' => 'Tumblr Url',
                'name' => 'social_tumblr',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b7d196d6c',
                'label' => 'Twitter Url',
                'name' => 'social_twitter',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b7dc96d6d',
                'label' => 'Viddler Url',
                'name' => 'social_viddler',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b7e896d6e',
                'label' => 'Vimeo Url',
                'name' => 'social_vimeo',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b7f296d6f',
                'label' => 'Virb Url',
                'name' => 'social_virb',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b7fc96d70',
                'label' => 'Wordpress Url',
                'name' => 'social_wordpress',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b80696d71',
                'label' => 'Yahoo Url',
                'name' => 'social_yahoo',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b82496d72',
                'label' => 'Yelp Url',
                'name' => 'social_yelp',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b82a96d73',
                'label' => 'Youtube Url',
                'name' => 'social_youtube',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5187b83496d74',
                'label' => 'Zerply Url',
                'name' => 'social_zerply',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_page-setup',
        'title' => 'Page Setup',
        'fields' => array (
            array (
                'key' => 'field_5163303c00d24',
                'label' => 'General',
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_516566ad5bab4',
                'label' => 'Page Type',
                'name' => 'page_type',
                'type' => 'select',
                'choices' => array (
                    'home' => 'Home Page',
                    'blog' => 'Blog',
                    'half page' => 'Half Page',
                    'page' => 'Page',
                    'collection' => 'Collection',
                    'gallery' => 'Gallery',
                    'video' => 'Video',
                ),
                'default_value' => 'page',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_516bf9d523913',
                'label' => 'Page Width',
                'name' => 'page_width',
                'type' => 'select',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'page',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'choices' => array (
                    'normal' => 'Normal',
                    'full' => 'Full',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_51716c7584a58',
                'label' => 'Claim Message Line 1',
                'name' => 'claim_message_line_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'home',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_51716ccf84a59',
                'label' => 'Center content',
                'name' => 'claim_message_line_2',
//                'type' => 'text',
                'type' => 'wysiwyg',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'home',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_51716d0384a5a',
                'label' => 'Page Button',
                'name' => 'page_button',
                'type' => 'relationship',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'home',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'post_type' => array (
                    0 => 'page',
                ),
                'taxonomy' => array (
                    0 => 'all',
                ),
                'max' => 1,
            ),
            array (
                'key' => 'field_516ffde874f18',
                'label' => 'Display News Sidebar',
                'name' => 'display_news_sidebar',
                'type' => 'checkbox',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'home',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'choices' => array (
                    'display' => 'Display',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_516ea7d120c17',
                'label' => 'Boxes Pages',
                'name' => 'boxes_pages',
                'type' => 'relationship',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'home',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'post_type' => array (
                    0 => 'page',
                ),
                'taxonomy' => array (
                    0 => 'all',
                ),
                'max' => 4,
            ),
            array (
                'key' => 'field_516ea81e295f4',
                'label' => 'Box 1 Icon',
                'name' => 'box_1_icon',
                'type' => 'select',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'home',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'choices' => array (
                    'banknote' => 'banknote',
                    'bubble' => 'bubble',
                    'bulb' => 'bulb',
                    'calendar' => 'calendar',
                    'camera' => 'camera',
                    'clip' => 'clip',
                    'clock' => 'clock',
                    'cloud' => 'cloud',
                    'cup' => 'cup',
                    'data' => 'data',
                    'diamond' => 'diamond',
                    'display' => 'display',
                    'eye' => 'eye',
                    'fire' => 'fire',
                    'food' => 'food',
                    'heart' => 'heart',
                    'key' => 'key',
                    'lab' => 'lab',
                    'like' => 'like',
                    'location' => 'location',
                    'lock' => 'lock',
                    'mail' => 'mail',
                    'megaphone' => 'megaphone',
                    'music' => 'music',
                    'news' => 'news',
                    'note' => 'note',
                    'paperplane' => 'paperplane',
                    'params' => 'params',
                    'pen' => 'pen',
                    'phone' => 'phone',
                    'photo' => 'photo',
                    'search' => 'search',
                    'settings' => 'settings',
                    'shop' => 'shop',
                    'sound' => 'sound',
                    'stack' => 'stack',
                    'star' => 'star',
                    'study' => 'study',
                    't shirt' => 't shirt',
                    'tag' => 'tag',
                    'trash' => 'trash',
                    'truck' => 'truck',
                    'tv' => 'tv',
                    'user' => 'user',
                    'vallet' => 'vallet',
                    'video' => 'video',
                    'vynil' => 'vynil',
                    'world' => 'world',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_516fc479dd121',
                'label' => 'Box 1 Message',
                'name' => 'box_1_message',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'home',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_516ebe1f95edd',
                'label' => 'Box 2 Icon',
                'name' => 'box_2_icon',
                'type' => 'select',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'home',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'choices' => array (
                    'banknote' => 'banknote',
                    'bubble' => 'bubble',
                    'bulb' => 'bulb',
                    'calendar' => 'calendar',
                    'camera' => 'camera',
                    'clip' => 'clip',
                    'clock' => 'clock',
                    'cloud' => 'cloud',
                    'cup' => 'cup',
                    'data' => 'data',
                    'diamond' => 'diamond',
                    'display' => 'display',
                    'eye' => 'eye',
                    'fire' => 'fire',
                    'food' => 'food',
                    'heart' => 'heart',
                    'key' => 'key',
                    'lab' => 'lab',
                    'like' => 'like',
                    'location' => 'location',
                    'lock' => 'lock',
                    'mail' => 'mail',
                    'megaphone' => 'megaphone',
                    'music' => 'music',
                    'news' => 'news',
                    'note' => 'note',
                    'paperplane' => 'paperplane',
                    'params' => 'params',
                    'pen' => 'pen',
                    'phone' => 'phone',
                    'photo' => 'photo',
                    'search' => 'search',
                    'settings' => 'settings',
                    'shop' => 'shop',
                    'sound' => 'sound',
                    'stack' => 'stack',
                    'star' => 'star',
                    'study' => 'study',
                    't shirt' => 't shirt',
                    'tag' => 'tag',
                    'trash' => 'trash',
                    'truck' => 'truck',
                    'tv' => 'tv',
                    'user' => 'user',
                    'vallet' => 'vallet',
                    'video' => 'video',
                    'vynil' => 'vynil',
                    'world' => 'world',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_516fc494dd122',
                'label' => 'Box 2 Message',
                'name' => 'box_2_message',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'home',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_516ebe2b95ede',
                'label' => 'Box 3 Icon',
                'name' => 'box_3_icon',
                'type' => 'select',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'home',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'choices' => array (
                    'banknote' => 'banknote',
                    'bubble' => 'bubble',
                    'bulb' => 'bulb',
                    'calendar' => 'calendar',
                    'camera' => 'camera',
                    'clip' => 'clip',
                    'clock' => 'clock',
                    'cloud' => 'cloud',
                    'cup' => 'cup',
                    'data' => 'data',
                    'diamond' => 'diamond',
                    'display' => 'display',
                    'eye' => 'eye',
                    'fire' => 'fire',
                    'food' => 'food',
                    'heart' => 'heart',
                    'key' => 'key',
                    'lab' => 'lab',
                    'like' => 'like',
                    'location' => 'location',
                    'lock' => 'lock',
                    'mail' => 'mail',
                    'megaphone' => 'megaphone',
                    'music' => 'music',
                    'news' => 'news',
                    'note' => 'note',
                    'paperplane' => 'paperplane',
                    'params' => 'params',
                    'pen' => 'pen',
                    'phone' => 'phone',
                    'photo' => 'photo',
                    'search' => 'search',
                    'settings' => 'settings',
                    'shop' => 'shop',
                    'sound' => 'sound',
                    'stack' => 'stack',
                    'star' => 'star',
                    'study' => 'study',
                    't shirt' => 't shirt',
                    'tag' => 'tag',
                    'trash' => 'trash',
                    'truck' => 'truck',
                    'tv' => 'tv',
                    'user' => 'user',
                    'vallet' => 'vallet',
                    'video' => 'video',
                    'vynil' => 'vynil',
                    'world' => 'world',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_516fc4a2dd123',
                'label' => 'Box 3 Message',
                'name' => 'box_3_message',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'home',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_516ebe3695edf',
                'label' => 'Box 4 Icon',
                'name' => 'box_4_icon',
                'type' => 'select',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'home',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'choices' => array (
                    'banknote' => 'banknote',
                    'bubble' => 'bubble',
                    'bulb' => 'bulb',
                    'calendar' => 'calendar',
                    'camera' => 'camera',
                    'clip' => 'clip',
                    'clock' => 'clock',
                    'cloud' => 'cloud',
                    'cup' => 'cup',
                    'data' => 'data',
                    'diamond' => 'diamond',
                    'display' => 'display',
                    'eye' => 'eye',
                    'fire' => 'fire',
                    'food' => 'food',
                    'heart' => 'heart',
                    'key' => 'key',
                    'lab' => 'lab',
                    'like' => 'like',
                    'location' => 'location',
                    'lock' => 'lock',
                    'mail' => 'mail',
                    'megaphone' => 'megaphone',
                    'music' => 'music',
                    'news' => 'news',
                    'note' => 'note',
                    'paperplane' => 'paperplane',
                    'params' => 'params',
                    'pen' => 'pen',
                    'phone' => 'phone',
                    'photo' => 'photo',
                    'search' => 'search',
                    'settings' => 'settings',
                    'shop' => 'shop',
                    'sound' => 'sound',
                    'stack' => 'stack',
                    'star' => 'star',
                    'study' => 'study',
                    't shirt' => 't shirt',
                    'tag' => 'tag',
                    'trash' => 'trash',
                    'truck' => 'truck',
                    'tv' => 'tv',
                    'user' => 'user',
                    'vallet' => 'vallet',
                    'video' => 'video',
                    'vynil' => 'vynil',
                    'world' => 'world',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_516fc4addd124',
                'label' => 'Box 4 Message',
                'name' => 'box_4_message',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'home',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_51750b36bca43',
                'label' => 'Images',
                'name' => 'images',
                'type' => 'gallery',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'gallery',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'preview_size' => 'thumbnail',
            ),
            array (
                'key' => 'field_5175561179e09',
                'label' => 'Images Autoplay',
                'name' => 'images_autoplay',
                'type' => 'checkbox',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'gallery',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'choices' => array (
                    1 => 'Auto switch images after delay',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_51754f891b416',
                'label' => 'Images Delay',
                'name' => 'images_delay',
                'type' => 'number',
                'instructions' => 'Min 4000',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'gallery',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => 7500,
            ),
            array (
                'key' => 'field_51769d45000d7',
                'label' => 'Collection Pages',
                'name' => 'collection_pages',
                'type' => 'relationship',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'collection',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'post_type' => array (
                    0 => 'page',
                ),
                'taxonomy' => array (
                    0 => 'all',
                ),
                'max' => '',
            ),
            array (
                'key' => 'field_5176a6d88ecd1',
                'label' => 'Display Tags',
                'name' => 'display_tags',
                'type' => 'checkbox',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'collection',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'choices' => array (
                    1 => 'Display Collection Tags',
                ),
                'default_value' => 1,
            ),
            array (
                'key' => 'field_517a73557f547',
                'label' => 'Category',
                'name' => 'category',
                'type' => 'taxonomy',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'blog',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'taxonomy' => 'category',
                'field_type' => 'select',
                'allow_null' => 1,
                'load_save_terms' => 0,
                'return_format' => 'object',
            ),
            array (
                'key' => 'field_517e9a03bcd96',
                'label' => 'Page Video Url',
                'name' => 'page_video_url',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'video',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'formatting' => 'none',
            ),
            array (
                'key' => 'field_517e9aed59c37',
                'label' => 'Page Video Autoplay',
                'name' => 'page_video_autoplay',
                'type' => 'true_false',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'video',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'message' => 'Play the video after the page is loaded',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_517fe0d2dc0f7',
                'label' => 'Second Column Content',
                'name' => 'second_column_content',
                'type' => 'wysiwyg',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'half page',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'toolbar' => 'full',
                'media_upload' => 'yes',
            ),
            array (
                'key' => 'field_5182249cd60d5',
                'label' => 'Hide Sidebar',
                'name' => 'hide_sidebar',
                'type' => 'true_false',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'page',
                        ),
                        array (
                            'field' => 'field_516566ad5bab4',
                            'operator' => '==',
                            'value' => 'blog',
                        ),
                    ),
                    'allorany' => 'any',
                ),
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_5163301ab295b',
                'label' => 'Background',
                'name' => 'background',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_51633060e312b',
                'label' => 'Background Type',
                'name' => 'background_type',
                'type' => 'select',
                'choices' => array (
                    'images' => 'Images',
                    'video' => 'Video',
                    'color' => 'Color',
                ),
                'default_value' => '',
                'allow_null' => 1,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_51641d8f9e18e',
                'label' => 'Background Images',
                'name' => 'background_images',
                'type' => 'gallery',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_51633060e312b',
                            'operator' => '==',
                            'value' => 'images',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'preview_size' => 'thumbnail',
            ),
            array (
                'key' => 'field_516421a97eed7',
                'label' => 'Background Images Delay',
                'name' => 'background_images_delay',
                'type' => 'number',
                'instructions' => 'In milliseconds (min: 2000)',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_51633060e312b',
                            'operator' => '==',
                            'value' => 'images',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_516420d7d8c83',
                'label' => 'Background Color',
                'name' => 'background_color',
                'type' => 'color_picker',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_51633060e312b',
                            'operator' => '==',
                            'value' => 'color',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_51641f8e15b89',
                'label' => 'Video Url',
                'name' => 'video_url',
                'type' => 'text',
                'instructions' => 'Url of the background video. Only Youtube or Vimeo.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_51633060e312b',
                            'operator' => '==',
                            'value' => 'video',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_51641fcd15b8a',
                'label' => 'Video Url Replacement',
                'name' => 'video_url_replacement',
                'type' => 'image',
                'instructions' => 'Image to display on mobile devices instead of video.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_51633060e312b',
                            'operator' => '==',
                            'value' => 'video',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
            ),
            array (
                'key' => 'field_51641dc230a23',
                'label' => 'Pixel Pattern',
                'name' => 'pixel_pattern',
                'type' => 'true_false',
                'message' => 'Display a pixellated overlay on the background',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_51641f630c4bb',
                'label' => 'Background Color Overlay',
                'name' => 'background_color_overlay',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_51642278445dd',
                'label' => 'Background Overlay Opacity',
                'name' => 'background_overlay_opacity',
                'type' => 'number',
                'instructions' => 'min: 0, max: 100',
                'default_value' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_post-options',
        'title' => 'Post Options',
        'fields' => array (
            array (
                'key' => 'field_517e6a65107b2',
                'label' => 'General',
                'name' => 'general',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_517117a421132',
                'label' => 'Excerpt',
                'name' => 'excerpt',
                'type' => 'text',
                'instructions' => 'Text displayed in posts list.',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_517e66027812d',
                'label' => 'Page Width',
                'name' => 'page_width',
                'type' => 'select',
                'choices' => array (
                    'normal' => 'Normal',
                    'full' => 'Full',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_517e81e079b2d',
                'label' => 'Hide Sidebar',
                'name' => 'hide_sidebar',
                'type' => 'true_false',
                'message' => 'Hide Sidebar',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_517e6a6f107b3',
                'label' => 'Background',
                'name' => 'background',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_517e6ba93502b',
                'label' => 'Background Type',
                'name' => 'background_type',
                'type' => 'select',
                'choices' => array (
                    'images' => 'Images',
                    'video' => 'Video',
                    'color' => 'Color',
                ),
                'default_value' => '',
                'allow_null' => 1,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_517e6bc53502c',
                'label' => 'Background Images',
                'name' => 'background_images',
                'type' => 'gallery',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_517e6ba93502b',
                            'operator' => '==',
                            'value' => 'images',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'preview_size' => 'thumbnail',
            ),
            array (
                'key' => 'field_517e6be93502d',
                'label' => 'Background Images Delay',
                'name' => 'background_images_delay',
                'type' => 'number',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_517e6ba93502b',
                            'operator' => '==',
                            'value' => 'images',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_517e6bfc3502e',
                'label' => 'Background Color',
                'name' => 'background_color',
                'type' => 'color_picker',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_517e6ba93502b',
                            'operator' => '==',
                            'value' => 'color',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_517e6c5fc946c',
                'label' => 'Video Url',
                'name' => 'video_url',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_517e6ba93502b',
                            'operator' => '==',
                            'value' => 'video',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_517e6c83c946d',
                'label' => 'Video Url Replacement',
                'name' => 'video_url_replacement',
                'type' => 'image',
                'instructions' => 'Image to display on mobile devices instead of video.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_517e6ba93502b',
                            'operator' => '==',
                            'value' => 'video',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'save_format' => 'url',
                'preview_size' => 'thumbnail',
            ),
            array (
                'key' => 'field_517e6cb290d84',
                'label' => 'Pixel Pattern',
                'name' => 'pixel_pattern',
                'type' => 'true_false',
                'message' => 'Display a pixellated overlay on the background',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_517e6cf60300c',
                'label' => 'Background Color Overlay',
                'name' => 'background_color_overlay',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_517e6d100300d',
                'label' => 'Background Overlay Opacity',
                'name' => 'background_overlay_opacity',
                'type' => 'number',
                'instructions' => 'min: 0, max: 100',
                'default_value' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_track-setup',
        'title' => 'Track Setup',
        'fields' => array (
            array (
                'key' => 'field_5164054d924d9',
                'label' => 'Advice',
                'name' => 'message',
                'type' => 'message',
                'message' => 'You <strong>must</strong> provide an mp3 <strong>and</strong> an ogg file in order to play the audio track in every browser.',
            ),
            array (
                'key' => 'field_51640712ad223',
                'label' => 'track index',
                'name' => 'track_index',
                'type' => 'number',
                'default_value' => 1,
            ),
            array (
                'key' => 'field_51640528dec0e',
                'label' => 'Upload',
                'name' => 'upload',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_51640034dec0c',
                'label' => 'mp3 file',
                'name' => 'mp3_file',
                'type' => 'file',
                'save_format' => 'url',
            ),
            array (
                'key' => 'field_51640516dec0d',
                'label' => 'ogg file',
                'name' => 'ogg_file',
                'type' => 'file',
                'save_format' => 'url',
            ),
            array (
                'key' => 'field_51640537dec0f',
                'label' => 'Url',
                'name' => 'url',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_516405dbd1d47',
                'label' => 'custom mp3 file url',
                'name' => 'custom_mp3_file_url',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_516405f2d1d48',
                'label' => 'custom ogg file url',
                'name' => 'custom_ogg_file_url',
                'type' => 'text',
                'default_value' => '',
                'formatting' => 'html',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'audiotracks',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_fonts',
        'title' => 'Fonts',
        'fields' => array (
            array (
                'key' => 'field_5162f6103f067',
                'label' => 'Content',
                'name' => 'content',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5162f4103a571',
                'label' => 'Google Webfont Name',
                'name' => 'google_webfont_name_default',
                'type' => 'text',
                'instructions' => 'The name of the font family for content text areas - Available fonts are listed on <a href="http://www.google.com/fonts/" target="_blank">Google Webfonts</a>.',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5162f67c7fe26',
                'label' => 'Font Styles',
                'name' => 'font_styles_default',
                'type' => 'checkbox',
                'choices' => array (
                    100 => 'Ultra Light',
                    200 => 'Light',
                    300 => 'Book',
                    500 => 'Medium',
                    700 => 'Bold',
                    900 => 'Ultra Bold',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_5162f65c971d5',
                'label' => 'Headings',
                'name' => 'headings',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5162f531ddad8',
                'label' => 'Google Webfont Name',
                'name' => 'google_webfont_name_headings',
                'type' => 'text',
                'instructions' => 'The name of the font family for headings - Available fonts are listed on <a href="http://www.google.com/fonts/" target="_blank">Google Webfonts</a>.',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5162f6e8e3ba8',
                'label' => 'Font Styles',
                'name' => 'font_styles_headings',
                'type' => 'checkbox',
                'choices' => array (
                    100 => 'Ultra Light',
                    200 => 'Light',
                    300 => 'Book',
                    500 => 'Medium',
                    700 => 'Bold',
                    900 => 'Ultra Bold',
                ),
                'default_value' => '',
            ),
            array (
                'key' => 'field_5163d5e424e2f',
                'label' => 'Menu',
                'name' => 'menu',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5163d62924e30',
                'label' => 'Google Webfont Name',
                'name' => 'google_webfont_name_menu',
                'type' => 'text',
                'instructions' => 'The name of the font family for the menu area - Available fonts are listed on <a href="http://www.google.com/fonts/" target="_blank">Google Webfonts</a>.',
                'default_value' => '',
                'formatting' => 'html',
            ),
            array (
                'key' => 'field_5163d65724e31',
                'label' => 'Font Styles',
                'name' => 'font_styles_menu',
                'type' => 'checkbox',
                'choices' => array (
                    100 => 'Ultra Light',
                    200 => 'Light',
                    300 => 'Book',
                    500 => 'Medium',
                    700 => 'Bold',
                    900 => 'Ultra Bold',
                ),
                'default_value' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 1,
    ));
    register_field_group(array (
        'id' => 'acf_colors',
        'title' => 'Colors',
        'fields' => array (
            array (
                'key' => 'field_5183ea8124a8a',
                'label' => 'General',
                'name' => 'general',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5163233b225d7',
                'label' => 'Text',
                'name' => 'color-text',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e1cbcc5a6',
                'label' => 'Anchors',
                'name' => 'color-anchor',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e3b6ed5e8',
                'label' => 'Headings',
                'name' => 'color-headings',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5163205c84be2',
                'label' => 'Background',
                'name' => 'color-background',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e42093261',
                'label' => 'Main Color',
                'name' => 'color-01',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e512f1c03',
                'label' => 'Second Color',
                'name' => 'color-02',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_516329f7be008',
                'label' => 'Logo Background',
                'name' => 'color-background-logo',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5163d2fae5ce8',
                'label' => 'Footer Background',
                'name' => 'color-background-footer',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_51642fbfe0627',
                'label' => 'Menu - Links',
                'name' => 'color-menu-anchors',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5163de162209b',
                'label' => 'Menu - Mouse Over',
                'name' => 'color-background-menu-over',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183df4f4f080',
                'label' => 'Buttons',
                'name' => 'color-button',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183dfc47df96',
                'label' => 'Buttons Text',
                'name' => 'color-button-text',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e0464230e',
                'label' => 'Borders',
                'name' => 'color-border',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e8b3452e0',
                'label' => 'Scrollbar Background',
                'name' => 'color-scrollbar-track-background',
                'type' => 'color_picker',
                'instructions' => 'Only Chrome and Safari.',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e90515c18',
                'label' => 'Scrollbar Track',
                'name' => 'color-scrollbar-track',
                'type' => 'color_picker',
                'instructions' => 'Only Chrome and Safari',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183ea9a24a8b',
                'label' => 'Sections',
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5183e3ccebbe2',
                'label' => 'Sidebar Background',
                'name' => 'color-sidebar',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e3f4ca42b',
                'label' => 'Home Boxes Text',
                'name' => 'color-home-boxes',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e5ae37bc2',
                'label' => 'Home Boxes Background',
                'name' => 'color-home-boxes-bkg',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e6112140a',
                'label' => 'Home Boxes Background - Mouse Over',
                'name' => 'color-home-boxes-bkg-over',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e66060940',
                'label' => 'Home Button',
                'name' => 'color-home-button',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e7a54180b',
                'label' => 'Home Button Text',
                'name' => 'color-home-button-text',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e6ac93559',
                'label' => 'Home Sidebar Background',
                'name' => 'color-aside-bkg',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e997b9e97',
                'label' => 'Page Content Background',
                'name' => 'color-page-content',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e9b7b9e98',
                'label' => 'Page Titles Background',
                'name' => 'color-background-titles',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183e9cfb9e99',
                'label' => 'Gallery Caption & Loader Background',
                'name' => 'color-gallery-caption-loader',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183ea134b2bf',
                'label' => 'Collection Tags Background',
                'name' => 'color-collection-tags',
                'type' => 'color_picker',
                'default_value' => '',
            ),
            array (
                'key' => 'field_5183ea394b2c0',
                'label' => 'Collection Items Background',
                'name' => 'color-collection-items-bkg',
                'type' => 'color_picker',
                'default_value' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 2,
    ));
}
