ª8R<?php exit; ?>a:1:{s:7:"content";O:8:"stdClass":24:{s:2:"ID";i:166;s:11:"post_author";s:1:"2";s:9:"post_date";s:19:"2013-08-08 06:14:20";s:13:"post_date_gmt";s:19:"2013-08-08 06:14:20";s:12:"post_content";s:37929:"Local.Mobi Terms of Service

Last Updated: January 2013

&nbsp;

1. THIS IS AN AGREEMENT BETWEEN YOU AND LOCAL.Mobi Pty LTD Local.Mobi Pty

LTD ("Local") provides users with a variety of mobile internet-based

services (the "Service" or "Services"), including, without limitation,

mobile websites to established website owners some of which may contain

Local.Mobi advertising, Internet navigation assistance web pages or

application results ("Results Pages") containing search results, localized

Events pages, and other content offered through www.local.mobi (the "Web

Site"), our mobile application(s) ("Mobile Application(s)"), as well as any

Web page that contains a Web-based search box provided by Local (a "Home

Page" and, together with the Web Site, Mobile Application(s) and any Results

Pages, the "Local Mobile Web Pages"). This Terms of Service page states the

terms and conditions under which you may use the Services and the Local

Mobile Web Pages (the "Terms of Service" or "Agreement"). Please read this

page carefully. This is an agreement between you and Local. In accessing the

Services and/or the Local Mobile Web Pages, you accept all the terms and

conditions of this Agreement. Our Terms of Service may change from time to

time, and those changes will be available for your review on most Local

Mobile Web Pages that you view, and on our web page located at

http://local.mobi/terms. Your continued use of our Services or Local Mobile

Web Pages after any such changes have been made will signify your assent to

the changed Terms of Service. If you do not accept these Terms of Service,

do not use the Services or Local Mobile Web Pages, and if applicable, delete

Mobile Application(s) immediately.

&nbsp;

Additional terms may apply to the use of some Services, and are disclosed in

the form of the posted guidelines or rules applicable to such Services (the

"Service-Specific Rules"), which may be modified from time to time. All such

Service-Specific Rules are hereby incorporated by reference into, and form

part of, this Agreement. If any provisions of this Agreement conflict with

any Service-Specific Rules, the terms of the applicable Service-Specific

Rules shall control.

LOCAL OFFERS THE SERVICE TO YOU CONDITIONED ON YOUR ACCEPTANCE WITHOUT

MODIFICATION OF THIS AGREEMENT. YOUR USE OF THE SERVICE CONSTITUTES YOUR

ACCEPTANCE OF THIS AGREEMENT. THIS AGREEMENT CONTAINS DISCLAIMERS OF

WARRANTIES AND LIABILITY (See Sections 18, 19, and 20); AND AN EXCLUSIVE

REMEDY (See Section 19). THESE PROVISIONS FORM AN ESSENTIAL BASIS OF OUR

AGREEMENT.

&nbsp;

2. HOW LOCAL MAY MODIFY THIS AGREEMENT AND THE SERVICES Local reserves the

right to change the terms, conditions, and notices under which it offers any

of its Services at any time, for any reason, and without notice, and such

modifications shall be deemed effective immediately upon posting of the

modified terms. You are responsible for regularly reviewing these Terms of

Service, and any Service-Specific Rules, because your continued use of the

Services or Local Mobile Web Pages following the posting of changes to this

Agreement or the Service-Specific Rules will mean you accept those changes.

In agreeing to the terms and conditions of these Terms of Service, you agree

that Local may at any time, in its sole and absolute discretion, without

prior notice to you, modify, cancel, update, reconfigure, supplement, limit,

terminate, or otherwise alter the Services or any part thereof, including as

between different users of the same Services, whether temporarily or

permanently.

&nbsp;

3. REGISTERING WITH LOCAL

In order to take advantage of certain features of the Services (including,

without limitation, the posting of reviews of businesses and the receipt of

newsletters and special offers from Local), you may be required to create an

account with Local (a "Local Account"). You represent and warrant that all

registration information provided by you in connection with accessing and/or

using the Services is true, accurate, current and complete at the time of

registration and you undertake to update all such registration information

if at any time during your use of the Services it becomes untrue or

inaccurate. Local's use of any personal information that you provide to

Local during the account creation process is governed by Local's privacy

policy, which may be reviewed at http://local.mobi/privacy

&nbsp;

When you create a Local Account, you agree to take full responsibility for

maintaining the confidentiality of your Local Account user name and

password, and for all activity that is generated by your Local Account.

Accordingly, you understand and agree that you will be liable for any

activity performed by any people using your Local Account. You agree to

immediately notify Local of any unauthorized use of your Local Account or

any other breach of security.

&nbsp;

4. SERVICES NOT INTENDED FOR CHILDREN

&nbsp;

The Services and Local Mobile Web Pages are not intended for children under

the age of 13. Children under the age of 13 are expressly prohibited from

creating an account with Local. By creating an account or using the

Services, you represent and warrant that you are at least 13 years old.

&nbsp;

5. NO COMMERCIAL, UNLAWFUL OR HARMFUL USE OF THE SERVICE

&nbsp;

The Local Mobile Web Pages are for your personal, non-commercial use only.

You may not reproduce, duplicate, copy, sell, resell, exploit or otherwise

use the Local Mobile Web Pages, any portion thereof, or any services or

products available thereunder for commercial purposes. You may not use the

Local Mobile Web Pages in any way that harms Local, its affiliates,

resellers, distributors, advertisers, service providers and/or suppliers

(each, a "Local Party" and collectively, the "Local Parties") or any

customer of a Local Party, as determined in Local's sole discretion. Without

limiting the generality of this Section, you will not use the Local Mobile

Web Pages in any manner that could damage, disable, overburden, or impair

any Local Mobile Web Page (or the network(s) connected to any Internet Web

Page) or interfere with any other party's use and enjoyment of the Service.

&nbsp;

You represent and warrant that your usage of the Services will only be for

lawful purposes and will be done in accordance with these Terms of Service,

any applicable Service-Specific Rules, and all applicable laws generally.

You also represent and warrant that you will not use any of the Local Mobile

Web Pages or Services to violate any law, regulation or ordinance or any

right of Local or any third party, including, without limitation, any right

of privacy, publicity, copyright, patent or trademark or other intellectual

property right. You further represent and warrant that you have the adequate

legal capacity to abide by these Terms of Service and any applicable

Service-Specific Rules.

&nbsp;

6. PROHIBITED ACTIVITIES

Without limiting the generality of Section 5, you will not use the Services,

or any Local Mobile Web Page (i) to violate or infringe upon the rights of

others in any way, (ii) to violate or facilitate the violation of any law or

to encourage others to violate any law, (iii) to send unsolicited bulk

e-mail and/or instant messages, (iv) to transmit, relay, or otherwise

communicate vulgar, unlawful, obscene, profane, indecent or otherwise

offensive or objectionable materials or information, (v) to falsify your

identity or impersonate another person; or (vi) to engage in conduct that

limits the use and enjoyment of the Services, or any part thereof, by other

users in any way, as determined by Local in its sole and absolute

discretion. You will not send automated queries of any sort to the Service

without express permission in advance from Local. Please note that "sending

automated queries" includes, among other things (a) using any software that

sends queries to the Service to determine how a web site or web page "ranks"

on the Service for various queries; (b) "meta-searching" the Service; (c)

performing "offline" searches on the Service; and (d) using software robots,

spiders, or other tools to "scrape" or automatically copy any portions of

the Web Site or Services.

You agree not to (1) reverse engineer, disassemble, alter, decompile,

duplicate, create derivative works from, make copies of, extract information

from, provide or distribute others with any portion of the Local Mobile Web

Pages or Services, or any information available on, extracted or derived

from the Local Mobile Web Pages or Services, or any part thereof; (2)

connect, use, attempt to connect or use in any way the Services, for

purposes other than your private, personal use in good faith and as

explicitly offered on our website, including without limitation for any

commercial purpose, such as, for instance, sending unsolicited

communications of any type or nature; (3) interfere, block, disable or

otherwise affect any advertising, advertising element, advertisement banner

window, links to other sites and services, or other features that constitute

an integral part of the Services; and (4) incorporate, integrate or

otherwise include any portion of the Services that is comprised of software

into any software, program or product that communicates, accesses, or

otherwise connects with the Services or any other instant messaging,

Internet, or online service. Finally, you may not authorize or assist any

third party to do any of the things described in this section.

&nbsp;

7. TERMINATION; VIOLATIONS; ACCESS RESTRICTION Local may terminate this

Agreement, or terminate or suspend your access to the Service at any time,

with or without cause, and with or without notice. Upon such termination or

suspension, your right to use the Service will immediately cease.

If you violate these Terms of Service in any way, including, without

limitation, by repeat infringement of copyrights, Local may, at its sole

discretion, terminate your account, remove or modify any account-related

content or access (including, but not limited to, reviews, newsletters, and

promotions), or take any other action that Local believes is appropriate.

Local may investigate violations of these Terms of Service and may involve

and cooperate with law enforcement authorities in prosecuting users of the

Services or Local Mobile Web Pages who are involved in such violations.

&nbsp;

8. POSTING CONTENT ON LOCAL

Certain of the Services may permit you to use your Local account to submit

reviews ("Reviews"), commentary, postings on message boards, data, text,

files, links, software, chat content, music, sound, photographs, graphics,

images, video, communication, messages or other materials and terms of

expression (collectively "User-Generated Content"). User-Generated Content

expressly excludes any personally identifiable and/or confidential

information that you provide to Local during the Local Account registration

process in Section 3 above. You agree that you will only post User-Generated

Content that you are legally entitled to publish, and Reviews that you

believe to be true, and that you will not purposely provide false or

misleading information in your Reviews.

Unless you have the express consent of the proper owner of any materials

that are copyrighted, trademarked or otherwise subject to a proprietary

right, you are not permitted to upload, post, or otherwise make such

materials available on or though the Services. You are solely responsible

for complying with all laws applicable to any User-Generated Content you

submit to the Service, including any Reviews, and for determining whether

any materials you wish to upload, post or otherwise make available on or

through the Services are subject to copyright, trademark or some other

proprietary right. Additionally, you are solely liable for any damages that

may arise as a result of any infringement of copyright, trademark or other

proprietary right, or any other damages that result from materials that you

upload, post or otherwise make available on or through the Services,

including without limitation any Reviews. You are solely responsible for any

User-Generated Content submitted to the Service from your Local Account.

Local reserves the right in its sole and absolute discretion to promulgate

such additional rules and policies which it deems necessary or appropriate

to govern the posting or submission of materials on or through the Services.

Local reserves the right, but has no obligation, to monitor disputes between

you and any business that you have reviewed. Local reserves the right in its

sole discretion and without obligation to monitor all User-Generated Content

to ensure conformity with the Local Terms of Service and any other rules,

policies or regulations as may be promulgated by Local from time to time it

its sole discretion, as well as any applicable laws, rules and regulations

of any government having proper jurisdiction over Local. Local has the

right, but not the obligation, to refuse to post, edit, delete, truncate or

to remove any User-Generated Content for any reason, including if the

User-Generated Content contains any of the following:

1. Offensive, harmful and/or abusive language, including without

limitation: expletives, profanities, obscenities, harassment, vulgarities,

sexually explicit language and hate speech (e.g., racist/discriminatory

speech)

2. References to illegal activity, malpractice, purposeful

overcharging, false advertising or health code violations (e.g., food

poisoning, foreign objects in food, etc.)

3. Reviews submitted by the reviewed business' employees (past or

present) or competitors, as determined by Local

4. Reviews that do not address the goods and services of the business

or Reviews with no qualitative value (e.g., "this place is great!"), as

determined by Local in its sole discretion.

5. Content commenting on other users or violating the privacy of other

users, as determined by Local, in its sole discretion

6. Content that contains personal attacks or describes physical

confrontations and/or sexual harassment

7. References to excessive damage caused by business or service to

person or property

8. Personal information or messages including, without limitation,

email addresses, URLs, phone numbers and postal addresses

9. Messages that are advertising or commercial in nature, amount to

spam, or are otherwise inappropriate based on the applicable subject matter

10. Language that violates the standards of good taste or the standards

of this website, as determined by Local in its sole discretion

11. Content determined by Local to be offensive, illegal, or to violate

any federal, state, or local law or regulation or the rights of any other

person or entity

12. Language intended to impersonate other users (including names of

other individuals) or offensive or inappropriate user names or signatures

13. Content that is not in English, that is encrypted or that contains

viruses, Trojan horses, worms, time bombs, cancelbots or other computer

programming routines that are intended to damage, interfere with, intercept

or appropriate any system, data or personal information

14. Content that otherwise violates these Terms of Service, or any

Service-Specific Rules, or that may harm or threaten the safety of other

users of the Service

15. Content that is false or intentionally misleading

&nbsp;

Nothing set forth above shall alter or diminish your responsibility with

respect to your User-Generated Content, as discussed herein. Reviews do not

reflect the views of Local or any of Local's subsidiaries or affiliated

companies or any of their respective employees, officers, directors, or

shareholders. Local does not assume responsibility or liability for any

Review or for any claims, damages, or losses resulting from any use of a

Review. You acknowledge and agree that, with respect to any conduct within

the Services, Local assumes and shall have no liability for any action or

failure to act on the part of Local.

BY USING OUR SERVICES, YOU AGREE THAT YOU WILL NOT SUBMIT ANY CONFIDENTIAL

INFORMATION OR MATERIALS TO OR THROUGH THE SERVICES OFFERED BY LOCAL. LOCAL

CANNOT AND DOES NOT AGREE TO MAINTAIN ANY INFORMATION OR MATERIALS YOU

SUBMIT TO OR THROUGH THE SERVICES AS CONFIDENTIAL.

You hereby grant Local, its subsidiaries, and/or affiliated companies an

irrevocable, unrestricted, royalty-free and perpetual worldwide license to

use, reproduce, broadcast, modify, adapt, translate, transmit, sell, store,

privately and publicly display, privately and publicly perform, create

derivative works based upon, distribute, and promote any and all

User-Generated Content that you submit, upload, post, send to or through all

or any portion of the Services, including without limitation, both within

the Services and such other products or services as Local may designate in

any medium now known or hereafter devised, for editorial, commercial,

promotional and all other purposes. To the extent you submit to Local any

ideas, concepts, know-how, techniques or other materials and/or information

of any kind, you agree that we are free to use any and all of the foregoing

without further permission or payment to you or any third party. You also

permit any user of the Services or Local Mobile Web Pages to access,

display, view, store and reproduce such User-Generated Content for personal

use. You waive any right to inspect or approve uses of any User-Generated

Content you submit or to be compensated for any such uses. Local is under no

obligation to give credit or pay any consideration to you for User-Generated

Content. You agree that Local owns all right, title, and interest in any

compilation, collective work or other derivative work created by Local using

or incorporating your User-Generated Content, irrespective of any right,

title or interest you or others may retain in your User-Generated Content.

By submitting User Generated-Content to or through the Services, you

represent and warrant that (i) you have the right to grant any and all

necessary licenses and rights provided herein, including without limitation,

all necessary copyright and other related rights to the User-Generated

Content, free and clear of all claims and encumbrances without violating the

rights of any person or entity, including any right to privacy or publicity,

and (ii) the User-Generated Content does not and shall not infringe on any

copyright or any other third party right nor violate any applicable law or

regulation.

&nbsp;

9. USE OF USER-GENERATED CONTENT

Local does not control, verify or endorse any User-Generated Content posted

by third-parties on the Service or Local Mobile Web Pages, and does not

guarantee the accuracy, integrity, timeliness or quality of such content.

You understand that, by using the Services or accessing the Local Mobile Web

Pages, you may be exposed to content that is offensive, indecent or

objectionable. You agree that you must evaluate and bear all risks

associated with the use of any content on the Service, including any

reliance on the content, integrity, and accuracy of such content. If you see

objectionable content or have any questions about this Agreement, please

contact Local at customerservice@local.mobi

&nbsp;

10. PROPRIETARY INFORMATION

As you use the Service, you should expect to receive, access or use

information, text, materials, graphics, software, sound, data, advertising,

and other content (collectively, "Content") provided by Local and other

Local Parties. You acknowledge and agree that the Local Mobile Web Pages and

any Content, Services or software available through or used in connection

with the Local Mobile Web Pages, including without limitation proprietary

databases, software, servers, components, and algorithms necessary to

operate and provide the Services, contain proprietary and confidential

information that is owned by one or more Local Parties, and is protected by

applicable intellectual property and other laws. You further acknowledge and

agree that Content made available via the Services or Local Mobile Web

Pages, but provided by third parties may be subject to separate Terms and

Conditions established by those third parties. Local's formatting of such

content, including the selection of such available content, and its

arrangement, enhancement and coordination is copyright protected by Local.

You further acknowledge and agree that Content contained in advertisements

or information presented to you through the Local Mobile Web Pages or by

advertisers is protected by copyright, trademarks, service marks, patents or

other proprietary rights and laws. Except as expressly authorized by the

appropriate Local Parties, you agree not to modify, rent, lease, loan, sell,

publish, transmit, distribute, create derivative works based on, or in any

way exploit the Services, the Local Mobile Web Pages, or any Content

available through or used in connection with the Local Mobile Web Pages, in

whole or in part. You are not permitted to store any portion of the content

of the Services in a computer unless it is for personal and non-commercial

use.

&nbsp;

11. TRADEMARK INFORMATION

You acknowledge and agree that Local.MobiR and other Local logos, products

and service names are or may be trademarks and/or service marks of Local

("Local Marks"). You agree that you will not display or use the Local Marks

in any manner, without the express written permission of Local. The names of

other products and companies contained within our Services may be the

trademarks or service marks of their respective owners. Nothing in these

Terms of Service grants you any license to use any trademark, service mark,

names or logos of Local, any Local Parties, or any third party.

&nbsp;

12. INFORMATION AVAILABLE FROM THE RESULTS PAGES Local and the Local Parties

do not warrant or guarantee the accuracy, completeness or timeliness of any

information available via the Services, or on any Local Mobile Web Page.

Local and the Local Parties do not authorize the use of information

available via the Services, or on any Local Mobile Web Page for any purpose

other than your personal uses. You may not resell, redistribute or use this

information for commercial purposes. Local does not endorse or recommend any

particular product or service.

&nbsp;

13. ADVERTISING

You understand and agree that some Services may include advertisements and

that these advertisements are necessary for Local to provide the Service.

&nbsp;

14.LINKS; THIRD PARTY SERVICES

Certain portions of the Services contain features and functionality that may

link to or be provided from a third party, including without limitation

third party websites, mobile websites, databases, applications, software,

programs, services, directories, servers, networks, and systems

(collectively, "Third Party Services"). Local provides access to these Third

Party Services to you as a convenience only and Local does not, in any way,

control or manage such Third Party Services. As such, Local is not

responsible for the content, functionality, accuracy, truthfulness, or

availability of such Third Party Services or any link contained therein. By

making such Third Party Services available via the Local Services, Local is

not endorsing or warranting such Third Party Services in any way.

Furthermore, Local does not endorse any product or service that may be

offered on or through such Third Party Services or through advertising

delivered on or through the Services. Under no circumstances shall the

access to or availability of such Third Party Services give rise to any

liability to anyone for any damage of whatever nature whatsoever.

&nbsp;

15. REQUESTS FOR REMOVAL OF LINKS FROM INDICES Local occasionally receives

requests to remove links from its indices that generate web results.

Although Local reserves the right to address such requests individually,

Local is generally not willing to remove any links from its indices.

&nbsp;

16. SECURITY AND PRIVACY LIMITATIONS

By use of any of the Services, you acknowledge that you are aware (1) that

data and information on the Services may be subject to forgery,

eavesdropping, tampering, sniffing, spamming, spoofing, password cracking,

harassment, fraud, electronic trespassing, hacking, nuking, system

contamination including viruses, worms and Trojan horses causing

unauthorized, damaging and/or harmful access to, or retrieval of,

information and data on your computer; (2) of security and privacy

limitations in the Services including without limitation the limitation of

security, privacy and authentication measures and features; (3) that the

security and privacy features available on the Services, are provided to you

as a convenience only and may not operate according to their description or

may not operate at all; and (4) that information, data or messages may not

reach their destination or may reach an erroneous address or recipient. You

acknowledge that, as with most Internet applications (i.e. e-mail), there

are certain risks associated with accepting or downloading files from or

through Local. Such risks include, but are not limited to, (1) damage to

your computer, (2) damage to any data or files stored on your computer, (3)

Local users viewing your IP address, and (4) files you share with other

Local users being redistributed and used without your knowledge.

&nbsp;

17. Subject to the requirements of any applicable legislation (including the

Australian Consumer Law), we do not provide refunds, if the provision of

Services to you is terminated by either party for any reason. In particular,

no refunds will be provided, if you have simply changed your mind in respect

of the provision of the Services by us to you

&nbsp;

18. LOCAL MAKES NO WARRANTY

THE LOCAL PARTIES PROVIDE THE SERVICES AND LOCAL MOBILE WEB PAGES "AS IS,"

"WITH ALL FAULTS" AND "AS AVAILABLE," AND THE ENTIRE RISK AS TO SATISFACTORY

QUALITY, PERFORMANCE, ACCURACY, SECURITY, AND EFFORT IS WITH YOU. TO THE

MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE LOCAL PARTIES MAKE NO

REPRESENTATIONS, WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED. THE LOCAL

PARTIES DISCLAIM ANY AND ALL WARRANTIES OR CONDITIONS, EXPRESS, STATUTORY

AND IMPLIED, INCLUDING WITHOUT LIMITATION (1) WARRANTIES OR CONDITIONS OF

MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, WORKMANLIKE EFFORT,

ACCURACY, TITLE AND NON-INFRINGEMENT, (2) WARRANTIES OR CONDITIONS ARISING

THROUGH COURSE OF DEALING OR USAGE OF TRADE, AND (3) WARRANTIES OR

CONDITIONS THAT ACCESS TO OR USE OF THE SERVICE WILL BE UNINTERRUPTED OR

ERROR-FREE.

LOCAL DOES NOT WARRANT THAT THE SERVICES, LOCAL MOBILE WEB PAGES OR WEB SITE

WILL OPERATE ERROR-FREE OR THAT THE WEB SITE OR ITS SERVER A RE FREE OF

COMPUTER VIRUSES OR OTHER HARMFUL MECHANISMS. YOU UNDERSTAND AND AGREE THAT

YOU DOWNLOAD OR OTHERWISE OBTAIN MATERIAL OR DATA THROUGH THE USE OF LOCAL'S

WEB PAGES OR SERVICES AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE

SOLELY RESPONSIBLE FOR ANY DAMAGES TO YOUR COMPUTER SYSTEM OR LOSS OF DATA

THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL OR DATA. IF YOUR USE OF THE

LOCAL MOBILE WEB SITE OR THE SERVICES RESULTS IN THE NEED FOR SERVICING OR

REPLACEMENT OF EQUIPMENT OR DATA, LOCAL IS NOT RESPONSIBLE FOR THOSE COSTS.

&nbsp;

19. LIABILITY LIMITATION; YOUR EXCLUSIVE REMEDY IN NO EVENT WILL ANY LOCAL

PARTY BE LIABLE FOR ANY DAMAGES, INCLUDING WITHOUT LIMITATION ANY INDIRECT,

CONSEQUENTIAL, SPECIAL, INCIDENTAL, OR PUNITIVE DAMAGES ARISING OUT OF,

BASED ON, OR RESULTING FROM THIS AGREEMENT OR YOUR USE OF THE SERVICE OR THE

LOCAL MOBILE WEB PAGES, EVEN IF SUCH LOCAL PARTY HAS BEEN ADVISED OF THE

POSSIBILITY OF SUCH DAMAGES. THE EXCLUSION OF DAMAGES UNDER THIS SECTION 19

IS INDEPENDENT OF YOUR EXCLUSIVE REMEDY AND SURVIVES IN THE EVENT SUCH

REMEDY FAILS OF ITS ESSENTIAL PURPOSE OR IS OTHERWISE DEEMED UNENFORCEABLE.

THESE LIMITATIONS AND EXCLUSIONS APPLY WITHOUT REGARD TO WHETHER THE DAMAGES

ARISE FROM (1) BREACH OF CONTRACT, (2) BREACH OF WARRANTY, (3) NEGLIGENCE,

OR (4) ANY OTHER CAUSE OF ACTION, TO THE EXTENT SUCH EXCLUSION AND

LIMITATIONS ARE NOT PROHIBITED BY APPLICABLE LAW. IF YOU ARE DISSATISFIED

WITH THE SERVICE, YOU DO NOT AGREE WITH ANY PART OF THIS AGREEMENT, OR YOU

HAVE ANY OTHER DISPUTE OR CLAIM WITH OR AGAINST ANY LOCAL PARTY WITH RESPECT

TO THIS AGREEMENT OR THE SERVICE, THEN YOUR SOLE AND EXCLUSIVE REMEDY IS TO

DISCONTINUE USING THE SERVICE.

&nbsp;

20. CHANGES TO THE SERVICE; ADDITIONAL LIABILITY LIMITATION WITHOUT LIMITING

THE GENERALITY OF SECTIONS 18 AND 19, YOU ACKNOWLEDGE AND AGREE THAT THE

LOCAL PARTIES ARE NOT RESPONSIBLE OR LIABLE FOR (1) ANY CONTENT PROVIDED BY

LOCAL OR ANY THIRD PARTIES, INCLUDING WITHOUT LIMITATION, ANY INFRINGING,

INACCURATE, OBSCENE, INDECENT, THREATENING, OFFENSIVE, DEFAMATORY, TORTIOUS,

OR ILLEGAL CONTENT, OR (2) ANY THIRD PARTY CONDUCT, TRANSMISSIONS OR DATA.

IN ADDITION, WITHOUT LIMITING THE GENERALITY OF SECTIONS 18 AND 19, YOU

ACKNOWLEDGE AND AGREE THAT LOCAL IS NOT RESPONSIBLE OR LIABLE FOR (1) ANY

VIRUSES OR OTHER DISABLING FEATURES THAT AFFECT YOUR ACCESS TO OR USE OF THE

SERVICE, (2) ANY INCOMPATIBILITY BETWEEN THE WEB SITE OR LOCAL MOBILE WEB

PAGES AND OTHER WEB SITES, SERVICES, SOFTWARE AND HARDWARE, (3) ANY DELAYS

OR FAILURES YOU MAY EXPERIENCE IN INITIATING, CONDUCTING OR COMPLETING ANY

TRANSMISSIONS OR TRANSACTIONS IN CONNECTION WITH THE SERVICES IN AN ACCURATE

OR TIMELY MANNER, (4) ANY LOSS OR LIABILITY RESULTING FROM ERRORS, OMISSIONS

OR MISSTATEMENTS IN ANY AND ALL INFORMATION OR SERVICES PROVIDED BY LOCAL TO

YOU, OR (5) ANY LOSSES, DAMAGES OR COSTS OF ANY TYPE ARISING OUT OF OR IN

ANY WAY CONNECTED WITH YOUR USE OF ANY SERVICES AVAILABLE FROM THIRD PARTIES

THROUGH LINKS CONTAINED ON THE LOCAL MOBILE WEB PAGES. YOU AGREE THAT YOU

MUST EVALUATE AND BEAR ALL RISKS ASSOCIATED WITH THE USE OF ANY CONTENT

PROVIDED BY LOCAL OR ANY THIRD PARTIES, INCLUDING ANY RELIANCE ON THE

ACCURACY OR COMPLETENESS OF SUCH CONTENT. THE LIMITATIONS, EXCLUSIONS AND

DISCLAIMERS IN SECTIONS 18, 19 AND 20 OF THIS AGREEMENT APPLY TO THE MAXIMUM

EXTENT PERMITTED BY APPLICABLE LAW, AND ARE NOT INTENDED TO DEPRIVE YOU OF

ANY MANDATORY PROTECTIONS PROVIDED TO YOU UNDER APPLICABLE LAW.

&nbsp;

21. INDEMNIFICATION

You agree to release, indemnify, defend and hold harmless Local, its parent,

subsidiaries and affiliates, and its and their shareholders, officers,

directors, employees, agents and advisors, from and against any and all

losses, liabilities, claims (including claims without legal merit or brought

in bad faith), demands, damages, costs or expenses, causes of action, suits,

proceedings, judgments, awards, executions and liens, including reasonable

attorneys' fees and costs (whether brought by third parties or otherwise)

(collectively, "Claims") due to or arising out of Content you submit, post,

transmit, modify or otherwise make available through the Services, your use

of the Services, your connection to the Services, any breach by you of this

Agreement, or your violation of any rights of another. Local reserves the

right, at its own expense, to assume the exclusive defense and control of

any matter subject to indemnification by you, which will not excuse your

indemnity obligations under this Section.

&nbsp;

22. CHOICE OF LAW AND LOCATION FOR RESOLVING DISPUTES If this Agreement is

with Local, claims for enforcement, breach or violation of duties or rights

under this Agreement will be adjudicated under the laws of the State of

California, without reference to conflict of laws principles. If this

Agreement is with a Local affiliate, claims for enforcement, breach or

violation of duties or rights under this Agreement will be adjudicated under

the laws of the place of incorporation for such Local affiliate, without

reference to conflict of laws principles. All other claims, including,

without limitation, claims under or for violation of consumer protection

laws, unfair competition laws, and in tort, will be adjudicated under the

laws of your state of residence in the United States, or, if you reside

outside the United States, under the laws of the country to which the

subject Local Mobile Web Pages are directed. If this Agreement is with

Local, you hereby irrevocably consent to the exclusive jurisdiction and

venue of state or federal courts in Orange County, California, USA in all

disputes arising out of or relating to this Agreement or the use of the

Service. If this Agreement is with a Local affiliate, you hereby consent to

the exclusive jurisdiction and venue of the courts located in the place of

incorporation for such Local affiliate in all disputes arising out of or

relating to this Agreement or the use of the Service. Use of the Service is

unauthorized in any jurisdiction that does not give effect to all provisions

of this Agreement, including without limitation this Section.

&nbsp;

23. INTERPRETING THE AGREEMENT; ASSIGNMENT If for any reason a court of

competent jurisdiction finds any provision or portion of this Agreement to

be unenforceable, the remainder of this Agreement will continue in full

force and effect. A printed version of this Agreement and any notice given

in electronic form shall be admissible in judicial or administrative

proceedings based upon or relating to this Agreement to the same extent and

subject to the same conditions as other business documents and records

originally generated and maintained in printed form. Local may assign this

Agreement, in whole or in part, at any time with or without notice to you.

You may not assign this Agreement. Except as expressly stated herein, this

Agreement constitutes the entire agreement between you and Local with

respect to the Service and it supersedes all prior or contemporaneous

communications and proposals, whether electronic, oral or written, between

you and Local with respect to the Service. The section titles in the

Agreement are solely used for the convenience of the parties and have no

legal or contractual significance.

&nbsp;

24. YOU HAVE LIMITED TIME TO BRING YOUR CLAIM YOU AND LOCAL AGREE THAT ANY

CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICE MUST COMMENCE

WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE

OF ACTION IS PERMANENTLY BARRED.

&nbsp;

&nbsp;

25. COPYRIGHT AND TRADEMARK NOTICES; OTHER ACKNOWLEDGEMENTS All contents of

the Local Mobile Web Pages are copyrighted by Local Corporation and/or its

suppliers, Suite 4, 337A Lennox St Richmond VIC, Australia, 3121. All rights

reserved. Local.mobi, the Local.mobi name and logos (old and new), and/or

other Local products and services referenced herein may also be either

trademarks or registered trademarks of Local in the United States and/or

other countries. The names of actual companies and products mentioned herein

may be the trademarks of their respective owners. The example companies,

organizations, products, domain names, e-mail addresses, logos, people,

places and events depicted herein are fictitious. No association with any

real company, organization, product, domain name, e-mail address, logo,

person, places or events is intended or should be inferred. Any rights not

expressly granted herein are reserved.

Certain portions of the content on the Local.Mobi Web Pages may be provided

by Acxiom Corporation. This information is proprietary to Acxiom Corporation

and is protected under U.S. copyright law and international treaty

provisions. This information is licensed for your personal or professional

use and may not be resold or provided to others. You may not distribute,

sell, rent, sublicense, or lease such information, in whole or in part, to

any third party; and you will not make such Acxiom information available, in

whole or in part, to any other user in any networked or time-sharing

environment, or transfer the information, in whole or in party, to any

computer other than the PC used to access this information.

&nbsp;

26. COPYRIGHT INFRINGEMENT

Local respects the intellectual property of others, and asks its users,

advertisers, licensors and service providers to do the same. If you believe

that your work has been copied and is accessible on or through the Service

in a way that constitutes copyright infringement, go to

http://local.mobi/copyright for instructions on how to report copyright

infringement to Local.";s:10:"post_title";s:20:"Terms and Conditions";s:12:"post_excerpt";s:0:"";s:11:"post_status";s:7:"publish";s:14:"comment_status";s:4:"open";s:11:"ping_status";s:4:"open";s:13:"post_password";s:0:"";s:9:"post_name";s:20:"terms-and-conditions";s:7:"to_ping";s:0:"";s:6:"pinged";s:0:"";s:13:"post_modified";s:19:"2013-08-08 06:15:59";s:17:"post_modified_gmt";s:19:"2013-08-08 06:15:59";s:21:"post_content_filtered";s:0:"";s:11:"post_parent";i:0;s:4:"guid";s:42:"http://resourcesat.local.mobi/?page_id=166";s:10:"menu_order";i:0;s:9:"post_type";s:4:"page";s:14:"post_mime_type";s:0:"";s:13:"comment_count";s:1:"0";s:6:"filter";s:3:"raw";}}